name: alina_mamonova

on:
  push:
    branches: [ "alina_mamonova/task-7" ]

jobs:
  task-7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.3go

      - name: Test DataBase
        working-directory: ./alina.mamonova/task-7
        run: go test -v ./internal/db/...

      - name: Test WiFi
        working-directory: ./alina.mamonova/task-7
        run: go test -v ./internal/wifi/...

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.3

      - name: Run golangci-lint
        working-directory: ./alina.mamonova/task-7
        run: golangci-lint run