name: anastasiya_soboleva

on:
  push:
    branches: [anastasiya.soboleva/task-7]

jobs:
  run-tests-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.2'

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.0

      - name: Run golangci-lint
        working-directory: ./anastasiya.soboleva/task-7
        run: golangci-lint run --config=../config/golangci.yml

      - name: Run db tests
        working-directory: ./anastasiya.soboleva/task-7
        run: go test -v ./internal/db/...

      - name: Run wifi tests
        working-directory: ./anastasiya.soboleva/task-7
        run: go test -v ./internal/wifi/...
