name: ErdemIstaev

on:
  push:
    branches: [ "task-7" ]
  workflow_dispatch:

jobs:

  Go-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.2

    - name: Test db
      working-directory: erdem.istaev/task-7
      run: go test ./internal/db

    - name: Test wifi
      working-directory: erdem.istaev/task-7
      run: go test ./internal/wifi

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.0

    - name: Run golangci-lint
      working-directory: erdem.istaev/task-7
      run: golangci-lint run --config='.golangci.yaml'