name: kirill_romanchuk

on:
  push:
    branches: [ "task-7" ]

jobs:
  Go-Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: TestDB
      working-directory: ./kirill.romanchuk/task-7
      run: go test -v ./internal/db/...

    - name: TestWiFi
      working-directory: ./kirill.romanchuk/task-7
      run: go test -v ./internal/wifi/...

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.3

    - name: Run golangci-lint
      working-directory: ./kirill.romanchuk/task-7
      run: golangci-lint run
