name: maksim_kladkovoj

on:
  push:
    branches: ["task-7"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test database
      working-directory: ./maksim.kladkovoj/task-7
      run: go test -v ./internal/db/...

    - name: Test wifi
      working-directory: ./maksim.kladkovoj/task-7
      run: go test -v ./internal/wifi/...

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.0

    - name: Linting on golangci-lint
      working-directory: ./maksim.kladkovoj/task-7
      run: golangci-lint run --config=./.golangci.yml
